### PR TITLE
feat: support Vite 4.0

### LINKED ISSUE #86: Support Vite v4
Vite 4 stable has been released. Maybe just need to bump the peer and dev dependencies.
```
 WARN  Issues with peer dependencies found
.
├─┬ vite-plugin-pages 0.27.1
│ └── ✕ unmet peer vite@"^2.0.0 || ^3.0.0-0": found 4.0.0
└─┬ vite-plugin-vue-layouts 0.7.0
  └── ✕ unmet peer vite@"^2.5.0 || ^3.0.0-0": found 4.0.0
```

### PR DESCRIPTION
**Pull request by kingyue737**
fix #86

### CODE REVIEW

**Comment by gewisser** [comment]
when will it merge?

**Comment by compilekaiten** [comment]
@JohnCampionJr Please merge this

**Comment by tidan-16** [comment]
Need merge

**Comment by vuduc0910** [comment]
Hi @JohnCampionJr , Please merge this.

**Comment by Xarunoba** [comment]
> @gewisser If you are using PNPM, you can suppress warnings via https://pnpm.io/package_json#pnpmpeerdependencyrulesallowedversions
> 
> I'm not familiar with yarn or npm. Maybe they have similar config.

For NPM users, you can temporarily suppress the warnings by using the setting the `legacy-peer-deps` to `true` in the configs. [NPM CI](https://docs.npmjs.com/cli/v8/commands/npm-ci)

Command:
`npm config set legacy-peer-deps=true --location=project`

Just delete the .npmrc file when support for Vite 4.0 is added. 😄

**Comment by MorganZ** [comment]
Hello Everyone,

Here a solution that works locally and on build agent, add this to your package json : 
`
  "overrides": {
    "vite-plugin-vue-layouts": {
      "vite": "^4.0.4"
    }
  }
`

Good luck

**Comment by tidan-16** [comment]
Is this package have support? I mean its just a simple merge to do

Should I look for an alternative package?

**Comment by Wakeful-Cloud** [comment]
> Is this package have support? I mean its just a simple merge to do
> 
> Should I look for an alternative package?

The [`@charrue/vite-plugin-vue-layouts`](https://github.com/charrue/vite-plugin-vue-layouts) fork was a drop-in replacement for me.

**Comment by AxelConceicao** [comment]
just click on the green button...

**Comment by JohnCampionJr** [comment]
So sorry everybody; looking at this right now - life's been crazy

**Pull request merged**
