### PR TITLE
fix(unplugin-vue-router)!: skip top-level route layout for index route children

### LINKED ISSUE #134: Nested page render the default layout even set to another layout
I'm using unplugin-vue-router.
图片
图片

pages and layout structure:
```
src/pages
├── about.vue
├── index.vue
└── nested
    └── index.vue

src/layouts
├── alpha.vue
└── default.vue
```

`about.vue` and `nested/index.vue` are set to `alpha` layout. But they have different behavior.

reproduce repo: https://github.com/Discreater/double-layout

### PR DESCRIPTION
**Pull request by markthree**
unplugin-vue-router adds a top-level route to the routing group, which we should skip, close #134

Although I've tested enough scenarios, feel free to let me know if you find any issues, plus this is a breaking change! 🤣

### CODE REVIEW

**Comment by JohnCampionJr** [comment]
@markthree how does this interact with #136 ?

**Comment by markthree** [comment]
> @markthree how does this interact with #136 ?
These are two separate pr's, to make it easier to merge without conflicts I will update this code

**Comment by markthree** [comment]
Done. If you want to fix both #134 and #97, merge this pr and close #136.

If you wish to fix only #97, merge #136 and close #137

**Review by JohnCampionJr — APPROVED** [review]

**Comment by JohnCampionJr** [comment]
@markthree thanks for this; all looks well to me.   I just tried all of the examples and all behaved :)

**Pull request merged**
